### ISSUE TITLE
Create a trait that provides a `isRelatedTo` method

### ISSUE THREAD

**Issue by DivineOmega** [langleyfoxall/helpers-laravel#16]
We could create a trait that provides a `isRelatedTo` method. It would use the `Models::areRelated()` from within a model, passing `$this` and a 2nd model. Example usage could be as follows:

```
$related = $wheel->isRelatedTo($car);
```

**Comment by dextermb** [comment]
This would be a pretty good idea. The more accessibility the better. I might push this out before the end of today unless someone else wanted to give it a shot!

**Comment by DivineOmega** [comment]
I'm already taking a look at this. :)

**Comment by DivineOmega** [comment]
@dextermb Is that what you had in mind?

**Comment by dextermb** [comment]
Yup!

💯 👍
