### ISSUE TITLE
Pick random model based on a weighted value

### ISSUE THREAD

**Issue by dextermb** [langleyfoxall/helpers-laravel#24]
I've come across a situation where I need to pick an instance of a model based on a weighted value. Myself and @DivineOmega think that this would be a useful to be built into our Models helper.

```
Models::randomByWeightedValue($models, $column);
```

I think you should be able to pass an array/collection of Models or a model class string (`Model::class`) which would then instantiate and call `all` selecting only the weighted column and ID. Once randomly selected return the Model.

We're looking for someone to take this on. It should be an easy enhancement to implement. The only complexity would be allowing as many different weight types possible. For example:

- Highest number lowest chance
- Highest number highest chance

cc @DivineOmega @wheatleyjj @JacobBrassington @AlexCatch

**Comment by DivineOmega** [comment]
@wheatleyjj Since you're taking this on, I've already written the required weighted random selection logic as a part of this package: https://github.com/DivineOmega/php-bucket-testing
