### ISSUE TITLE
Composer deprecation notice: Invalid PSR4 class declaration

### ISSUE THREAD

**Issue by robmilward** [langleyfoxall/helpers-laravel#35]
Looks as though the `NotRelatedException` has a namespace of `LangleyFoxall\Helpers\Exception`, except it's located within the `LangleyFoxall/Helpers/Exceptions` folder - note the '**s**'.

We just need to update the namespace to match it's physical location, and then release.

`
Deprecation Notice: Class LangleyFoxall\Helpers\Exception\NotRelatedException located in ./vendor/langleyfoxall/helpers-laravel/src/LangleyFoxall/Helpers/Exceptions/NotRelatedException.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
`

**Comment by DivineOmega** [comment]
Good catch Rob.

We'll have to watch out for this not only in packages, but also in projects themselves. These composer deprecation messages are sometimes missed because they appear above the package auto-discovery messages.
